language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
install:
  - npm install
before_script:
  - npm install grunt-cli istanbul -g
script:
  - istanbul cover grunt test
  - grunt coveralls
